### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by JCharante** [JCharante/flow#1]
Here are a list of MVP features. When an issue is made please have a link alongside the text

- [ ] Groups
    - [x] Group Page
        - [x] #36 Details Through API
        - [x] #38 Website
    - [x] Leave Queue
        - [x] #40 Through websocket
        - [x] #44 Through website
    - [x] Join Queue
        - [x] #40 Through websocket
        - [x] #44 Through website
    - [x] See Queue
        - [x] #40 Through websocket
        - [x] #44 Through website
    - [x] Create Group
        - [x] #12 Through restful api
        - [x] #30 Through website
    - [x] Get Invite Code
        - [x] #14  Through restful api
        - [x] #37 Through website
    - [x] Invite Link
        - [x] Through website
    - [x] See place in queue
        - [x] #40 Through websocket (through timestamps)
        - [x] #44 Through website
    - [x] View Groups you're in
        - [x] #18 Through restful api
        - [x] #21 Through website
    - [x] Join Group w/ a code
        - [x] #16 Through restful api
        - [x] #42 Through website
    - [x] #35 Join Group via a link
    - [ ] Leave Group
        - [x] #22 Through restful api
        - [ ] Through website
- [ ] Users
    - [x] A way to login to your account
        - [x] #4 Through a restful api
        - [x] #9 Through website
    - [x] A way to signup for an account
        - [x] #4 Through a restful api
        - [x] #10 Through website
    - [ ] A way to delete your account (to follow EU regulations)
        - [x] #8 Through a restful api
        - [ ] Through website
- [x] A landing page (to sell eventually the SaaS) #3 
- [x] Documentation #23
